BOOTLOADER_SRC_COMMON_PATH = $(BOOTLOADER_MODULE_PATH)/src

ifeq ("$(PLATFORM_ID)","103")
CSRC += $(BOOTLOADER_SRC_COMMON_PATH)/bluz/main.c
else ifeq ("$(PLATFORM_ID)","269")
CSRC += $(BOOTLOADER_SRC_COMMON_PATH)/bluz/main.c
else
CSRC += $(BOOTLOADER_SRC_COMMON_PATH)/main.c
endif

CSRC += $(BOOTLOADER_SRC_COMMON_PATH)/module_info.c

